# Generated by Django 3.2.9 on 2021-11-28 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_end_longitude_route_start_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
