# Generated by Django 3.2.9 on 2021-11-29 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_alter_pee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pee',
            name='route',
        ),
        migrations.AddField(
            model_name='pee',
            name='route_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
