# Generated by Django 3.2.9 on 2021-11-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20211129_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pee',
            name='route_id',
        ),
        migrations.AddField(
            model_name='pee',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maps.route'),
            preserve_default=False,
        ),
    ]
