# Generated by Django 3.2.9 on 2021-11-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20211129_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poop',
            old_name='poo_latitude',
            new_name='poop_latitude',
        ),
        migrations.RenameField(
            model_name='poop',
            old_name='poo_longitude',
            new_name='poop_longitude',
        ),
    ]
