# Generated by Django 3.2.9 on 2022-01-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_longitude',
        ),
    ]
