# Generated by Django 3.2.9 on 2022-01-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_alter_coordinate_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pee',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peeIcon', to='maps.route'),
        ),
    ]
