# Generated by Django 3.2.9 on 2022-01-27 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_alter_coordinate_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 3, 38, 17, 826671, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 3, 38, 24, 902087, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
