# Generated by Django 3.2.9 on 2022-01-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_alter_pee_route'),
        ('maps', '0017_auto_20220127_0338'),
    ]

    operations = [
    ]
