# Generated by Django 3.2.9 on 2022-02-01 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_merge_0017_alter_pee_route_0017_auto_20220127_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinkIcon', to='maps.route'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactionIcon', to='maps.route'),
        ),
        migrations.AlterField(
            model_name='poop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poopIcon', to='maps.route'),
        ),
    ]
