# Generated by Django 3.2.9 on 2022-03-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_auto_20220131_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
