# Generated by Django 3.2.9 on 2022-05-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_route_total_distance'),
        ('maps', '0020_route_total_distance 2'),
        ('maps', '0020_route_total_distance 3'),
    ]

    operations = [
    ]
